### ISSUE TITLE
fails to build with ghc-9.8.4

### ISSUE THREAD

**Issue by juhp** [konn/ghc-typelits-presburger#30]
```
       Building library for ghc-typelits-presburger-0.7.4.0..                                                                       
       [3 of 6] Compiling GHC.TypeLits.Presburger.Compat          
                                                                                                                                    
       /home/curators/work/unpack-dir/unpacked/ghc-typelits-presburger-0.7.4.0-26be899ae7923af199a222b0ddcab139e259e0a777fedcf84a752
e092a3c3226/src/GHC/TypeLits/Presburger/Compat.hs:525:10: error: [GHC-83865]                                                        
           • Couldn't match type ‘GHC.Word.Word64’ with ‘Int’                                                                       
             Expected: Unique -> Int                                                                                                
               Actual: Unique -> GHC.Word.Word64                                                                                    
           • In the expression: Unique.getKey                                                                                       
             In an equation for ‘getKey’: getKey = Unique.getKey                                                                    
           |                                                                                                                        
       525 | getKey = Unique.getKey                               
           |          ^^^^^^^^^^^^^
```

**Comment by konn** [comment]
Thank you for your report. This has been fixed in https://github.com/konn/ghc-typelits-presburger/pull/31.
